version: "3.8"
services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    ports:
     - "3000:3000"
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      DEBUG: robo-twitter:*
    command: npm run start
    depends_on:
      - zookeeper
      - kafka
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local